### ISSUE TITLE
Michael

### ISSUE THREAD

**Issue by realrichardhendricks** [Mvalverde00/Graphing-Calculator-3D#1]
sorry for the weird way of contacting you but an image of you has gone viral on twitter. here’s the  [post](https://twitter.com/iFuckdUrParents/status/1373781385740161027?s=20).

**Comment by Mvalverde00** [comment]
No worries, thanks for bringing this to my attention. I honestly find the situation somewhat funny. I wonder how they decided to use _that_ as the picture for their meme.

**Comment by realrichardhendricks** [comment]
no problem. i believe it came from a dox of another student in the picture. have a great day and stay safe!
